(* This helper creates a patched standalone COPY from an already downloaded
   baseline standalone. It never modifies its input. It is intended only for
   focused experiments; integrate modular files for actual development. *)
If[Length[$ScriptCommandLine] < 3, Print["Supply input.wl and a NEW output.wl path."]; Exit[2]];
input = $ScriptCommandLine[[-2]]; output = $ScriptCommandLine[[-1]];
If[FileExistsQ[output], Print["Output already exists."]; Exit[2]];
text = Import[input,"Text"];
If[!StringQ[text], Print["Input could not be read."]; Exit[2]];
edits = {"  backend = If[values === {}, Automatic, ReleaseHold[First[values]]];" -> "  backend = If[values === {}, OptionValue[AsymptoticExpansion, {}, \"Backend\"], ReleaseHold[First[values]]];","(* Explicit calculus for expansions.  A representation means\n   Offset + Prefactor (Jet + remainder), in the positive ScaleVariable.\n   The prefactor is exact; the jet precision is relative to that prefactor. *)\n\n" -> "(* Explicit calculus for expansions.  A representation means\n   Offset + Prefactor (Jet + remainder), in the positive ScaleVariable.\n   The prefactor is exact; the jet precision is relative to that prefactor. *)\n\n(* A necessary continuity screen, not a complete analyticity proof.\n   Refuse rather than silently substitute an endpoint value for a different\n   punctured-neighborhood limit. Both sides are checked deliberately: this\n   conservative patch does not introduce a new one-sided observable contract. *)\nseriesObservableEndpointContinuousQ[head_, center_, ass_] := Module[\n  {v = Unique[\"observableContinuity$\"], value, limits},\n  value = head[center];\n  limits = TimeConstrained[Quiet[{\n    Limit[head[center + v], v -> 0, Direction -> -1, Assumptions -> ass],\n    Limit[head[center - v], v -> 0, Direction -> -1, Assumptions -> ass]}], 2, $Failed];\n  ListQ[limits] && Length[limits] === 2 &&\n    And @@ (TrueQ[Simplify[# == value, ass]] & /@ limits)];\n\n","      cf = Function[k, If[k >= native[[4]] && k - native[[4]] + 1 <= Length[native[[3]]], native[[3, k - native[[4]] + 1]], 0]];" -> "      If[! TrueQ[native[[5]] > n],\n        fail[\"InsufficientNativeObservablePrecision\",\n          \"The native Taylor result does not reach the requested coefficient order.\",\n          <|\"RequestedCoefficientOrder\" -> n, \"NativeExclusiveOrder\" -> native[[5]]|>]];\n      If[!(parts[[3]] === {} && j[[2]] === Infinity) &&\n          ! seriesObservableEndpointContinuousQ[h, c, ass],\n        fail[\"UnprovedObservableContinuity\",\n          \"The observable is not proved continuous at its limiting argument on both real sides.\",\n          <|\"ObservableHead\" -> h, \"LimitingArgument\" -> c|>]];\n      cf = Function[k, If[k >= native[[4]] && k - native[[4]] + 1 <= Length[native[[3]]], native[[3, k - native[[4]] + 1]], 0]];"};
If[!And@@(StringCount[text,First[#]]===1& /@ edits),
  Print["Expected unique source anchors were not found."];Exit[2]];
text = Fold[StringReplace[#1,#2,1]&,text,edits];
Export[output,text,"Text"];
Print["Candidate standalone copy: ",output];
