"""Independent exact Python reference for the mathematics in RealInverseSeries.wl.

Weights are exact real SymPy expressions. No floating-point ordering is used.
Jets are dictionaries {relative_weight: polynomial_in_L}. A jet represents
sum s**weight * polynomial(log(s)), modulo weights >= cutoff.
This is a verification aid, not a Python parser for arbitrary input expressions.
"""
from __future__ import annotations
from dataclasses import dataclass
from functools import cmp_to_key
from itertools import product
from math import factorial
import sympy as S

L = S.Symbol('L', real=True)


def exact(x):
    return S.simplify(S.sympify(x))


def compare(a, b):
    d = exact(a-b)
    if d == 0:
        return 0
    if d.is_positive is True:
        return 1
    if d.is_negative is True:
        return -1
    raise ValueError(f'Cannot certify exact order: {a!s} versus {b!s}')


def clean(a, cutoff):
    out = {}
    for w, p in a.items():
        w = exact(w)
        if compare(w, cutoff) < 0:
            out[w] = S.expand(out.get(w, 0) + p)
    return {w: p for w, p in sorted(out.items(), key=cmp_to_key(lambda a,b: compare(a[0],b[0]))) if p != 0}


def add(a, b, cutoff):
    out = dict(a)
    for w, p in b.items():
        out[w] = S.expand(out.get(w, 0)+p)
    return clean(out, cutoff)


def scale(a, c):
    return {w: S.expand(c*p) for w,p in a.items() if S.expand(c*p) != 0}


def mul(a, b, cutoff):
    out = {}
    for wa, pa in a.items():
        for wb, pb in b.items():
            w = exact(wa+wb)
            if compare(w, cutoff) < 0:
                out[w] = S.expand(out.get(w,0)+pa*pb)
    return clean(out,cutoff)


def reciprocal(a, cutoff):
    """Reciprocal of a positive-order perturbation of a nonzero constant."""
    c = a.get(S.Integer(0), 0)
    if c == 0 or S.diff(c,L) != 0:
        raise ValueError('The constant block must be a nonzero scalar.')
    remainder = scale({w:p for w,p in a.items() if w != 0}, -1/c)
    term = {S.Integer(0): S.Integer(1)}
    out = scale(term,1/c)
    while term and remainder:
        term = mul(term,remainder,cutoff)
        out = add(out,scale(term,1/c),cutoff)
    return out


def compose(terms, u, cutoff):
    """Sum s**d (1+u)**a P(L+log(1+u)), with exact truncation.

    Local Taylor coefficients are generated by
    Q[0]=P, Q[k+1]=((a-k) Q[k]+D_L Q[k])/(k+1).
    """
    out = {}
    for d,a,p in terms:
        if compare(d,cutoff) >= 0:
            continue
        power = {S.Integer(0):S.Integer(1)}
        q = p
        k = 0
        while power:
            piece = {exact(d+w):S.expand(q*c) for w,c in power.items()}
            out = add(out,clean(piece,cutoff),cutoff)
            q = S.expand(((a-k)*q+S.diff(q,L))/(k+1))
            power = mul(power,u,exact(cutoff-d))
            k += 1
    return clean(out,cutoff)


@dataclass(frozen=True)
class Model:
    p: S.Expr
    c: S.Expr
    deltas: tuple
    polynomials: tuple

    def __post_init__(self):
        object.__setattr__(self,'p',exact(self.p))
        object.__setattr__(self,'c',exact(self.c))
        object.__setattr__(self,'deltas',tuple(exact(x) for x in self.deltas))
        object.__setattr__(self,'polynomials',tuple(S.expand(x) for x in self.polynomials))
        if compare(self.p,0)<=0 or compare(self.c,0)<=0:
            raise ValueError('Positive p and c are required.')
        if len(self.deltas)!=len(self.polynomials):
            raise ValueError('Mismatched generators.')
        if any(compare(d,0)<=0 for d in self.deltas):
            raise ValueError('All generator gaps must be positive.')
        if any(not p.is_polynomial(L) or p==0 for p in self.polynomials):
            raise ValueError('Nonzero logarithmic polynomials are required.')

    def index_set(self,A,limit=10000):
        A=exact(A)
        if compare(A,0)<=0:
            raise ValueError('A positive normalized cutoff is required.')
        found=[]
        def visit(j,ns,w):
            if j==len(self.deltas):
                found.append((tuple(ns),w))
                if len(found)>limit:
                    raise ValueError('Index limit exceeded.')
                return
            k=0
            while compare(exact(w+k*self.deltas[j]),A)<0:
                visit(j+1,ns+[k],exact(w+k*self.deltas[j]))
                k+=1
        visit(0,[],S.Integer(0))
        return found

    def coefficient(self,ns,w):
        n=sum(ns)
        if n==0:
            return S.Integer(1)
        q=S.prod(p**k for p,k in zip(self.polynomials,ns))
        for j in range(1,n):
            q=S.expand((1+w+self.p*j)*q+S.diff(q,L))
        return S.expand((-1)**n*q/(self.p**n*S.prod(S.factorial(k) for k in ns)))

    def lagrange(self,A):
        out={}
        for ns,w in self.index_set(A):
            out[w]=S.expand(out.get(w,0)+self.coefficient(ns,w))
        return clean(out,A)

    def forward_terms(self):
        return [(S.Integer(0),self.p,S.Integer(1))]+[(d,self.p+d,P) for d,P in zip(self.deltas,self.polynomials)]

    def residual(self,unit,A):
        u=add(unit,{S.Integer(0):-S.Integer(1)},A)
        return add(compose(self.forward_terms(),u,A),{S.Integer(0):-S.Integer(1)},A)

    def newton(self,A):
        """A separate constructive inverse: Newton in a truncated jet algebra."""
        A=exact(A)
        terms=self.forward_terms()
        dterms=[(d,a-1,S.expand(a*P+S.diff(P,L))) for d,a,P in terms]
        u={}
        trace=[]
        for k in range(100):
            residual=add(compose(terms,u,A),{S.Integer(0):-S.Integer(1)},A)
            trace.append({'step':k,'residual_weights':[str(w) for w in residual]})
            if not residual:
                return add(u,{S.Integer(0):S.Integer(1)},A),trace
            derivative=compose(dterms,u,A)
            correction=mul(residual,reciprocal(derivative,A),A)
            u=add(u,scale(correction,-1),A)
        raise RuntimeError('Newton iteration failed to terminate.')

    def border(self,A):
        indices=self.index_set(A)
        B={}
        for ns,w in indices:
            for j,d in enumerate(self.deltas):
                if compare(exact(w+d),A)>=0:
                    nn=list(ns); nn[j]+=1; nn=tuple(nn)
                    B[nn]=exact(w+d)
        return B

    def remainder(self,A):
        B=self.border(A)
        if not B:
            return S.oo,0
        ds=sorted(B.values(),key=cmp_to_key(compare))[0]
        degrees=[S.degree(P,L) for P in self.polynomials]
        k=max(sum(n*m for n,m in zip(ns,degrees)) for ns,d in B.items() if compare(d,ds)==0)
        return exact((1+ds)/self.p),int(k)

    def expression(self,unit,y):
        ell=S.log(y/self.c)/self.p
        return S.Add(*[(y/self.c)**((1+w)/self.p)*P.subs(L,ell) for w,P in unit.items()])
